### ISSUE TITLE
Error in process filter

### ISSUE THREAD

**Issue by pmiddend** [emacs-pe/lyrics.el#1]
I'm using emacs-25.0.95.1 (25 seems to be required). I executed `M-x lyrics` and then entered `Nine Inch Nails<ENTER>Hurt<ENTER>` and got the following message:

```
Contacting host: lyrics.wikia.com:80
error in process filter: lyrics-lyricswiki-api-callback: Symbol’s function definition is void: libxml-parse-xml-region
error in process filter: Symbol’s function definition is void: libxml-parse-xml-region
```

Edit 1: Oh, and I didn't enable libxml for xml parsing, I'll try that now. But shouldn't the package work nontheless?
Edit 2: With libxml2, it works

**Comment by PuercoPop** [comment]
@marsam maybe we could include an assert `(fboundp 'libxml-parse-xml-region)` at the beginning of the line and signal an appropriate error message if not found?
