### ISSUE TITLE
Incorrect `lyrics-backend` custom type

### ISSUE THREAD

**Issue by basil-conto** [emacs-pe/lyrics.el#3]
`lyrics.el` version: latest `master` of 2016-09-21

The user option `lyrics-backend` is currently defined as

```el
(defcustom lyrics-backend 'lyrics-lyricswiki
  "Function used to get lyrics.

This function should receive three parameters: Artist, Song,
Buffer \(optional\), and ultimately call `lyrics-show' to show
the lyrics."
  :type 'function
  :type (append '(choice)
                (mapcar (lambda (x) (list 'const :tag (car x) (cdr x))) lyrics-backends))
  :group 'lyrics)
```

There are two issues with its custom `:type` declaration:
1. It is specified twice, when only the last type specified takes effect
2. At the point of definition, `lyrics-backends` is still `nil`, so `(custom-variable-type 'lyrics-backend)` ends up being `(choice)`

In order to allow users to choose from all available backends, either
1. The `lyrics-backend` user option must be defined after all the backends in the file
2. The `lyrics-backends` variable should be statically defined at the start of the file
3. The `lyrics-backends` variable should be removed and replaced with a static custom `:type` for the `lyrics-backend` user option

If you let me know which approach you prefer I would be happy to provide a patch. Personally, I prefer approaches (1), which is more modular and dynamic, and (3), which is similar to other Emacs user options such as `message-send-mail-function`.

**Comment by marsam** [comment]
Hi, sorry for the late response. I've pushed a fix, tell me if it works for you.

**Comment by basil-conto** [comment]
No worries. I can confirm the issue is fixed now, thanks!
